### PR TITLE
Removing active main navigation highlighting

### PR DESCRIPTION
**Pull request by jszwedko**
From pattern library as it is very coupled with the specific usage of
the navigation in:

* The use of a list of specific menu items
* The use of jQuery (which is not included in the pattern library)
* The use of Drupal specific data attributes

Ultimately, I think it should be the responsibility of the application
where the pattern library is being used to set which menu item is active
since the method of determining this will vary quite a bit depending on
framework.

### CODE REVIEW

**Comment by jszwedko** [comment]
Companion PR: https://github.com/SFDigitalServices/sfgov/pull/214

**Comment by jszwedko** [comment]
I stumbled upon this when attempting to include the pattern lab JS in the noticing project failed due to the lack of jQuery. After considering it a bit, I came to the opinion that this particular logic better fits into the `sfgov` repo, but I'm curious what your thoughts are @aekong @josh-chou @henryjiang-sfgov @hshaosf 

This allows us to punt on the general question of whether we should be including jQuery in the pattern library, but I'll just state my opinion now in case it comes up again after this week 😢:

I think it'd be best to keep the number and size of JS libraries used in the pattern library to a minimum given that it will theoretically be included in every site we work on (increasing the overall size of those sites) and the fact that it needs to play nicely with whatever JS libraries or frameworks are use on those sites.

**Comment by jszwedko** [comment]
https://github.com/uswds/uswds/blob/develop/package.json#L58-L70 is an example of what we are including by way of depending on the uswds design system. They seem to err towards single purpose libraries (they even go so far as to only depend on the specific bit of lodash they are using).

**Comment by aekong** [comment]
this makes sense to me.  i suppose this is where the line is between a pattern library and a component library?

**Comment by aekong** [comment]
approved, merge it!

**Comment by jszwedko** [comment]
Found that I need to regenerate `components.js`; will do this before merging.

**Pull request closed without merging**
